import plugin from "tailwindcss/plugin";

// 定义一个 Tailwind 插件
const text_typographyPlugin = plugin(function ({ addUtilities }) {
  const newTypographyUtilities = {
    ".headline-h1": {
      fontSize: `${96 / 3.93}vw`,
      lineHeight: `${116 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h64": {
      fontSize: `${64 / 3.93}vw`,
      lineHeight: `${56 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h2": {
      fontSize: `${60 / 3.93}vw`,
      lineHeight: `${72 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h56": {
      fontSize: `${56 / 3.93}vw`,
      lineHeight: `${68 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h3": {
      fontSize: `${48 / 3.93}vw`,
      lineHeight: `${56 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h4": {
      fontSize: `${40 / 3.93}vw`,
      lineHeight: `${48 / 3.93}vw`,
      letterSpacing: `${0.2 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h5": {
      fontSize: `${32 / 3.93}vw`,
      lineHeight: `${38 / 3.93}vw`,
      letterSpacing: `${0.25 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h6": {
      fontSize: `${24 / 3.93}vw`,
      lineHeight: `${28 / 3.93}vw`,
      letterSpacing: `${0 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h7": {
      fontSize: `${20 / 3.93}vw`,
      lineHeight: `${30 / 3.93}vw`,
      letterSpacing: `${0.15 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h8": {
      fontSize: `${16 / 3.93}vw`,
      lineHeight: `${24 / 3.93}vw`,
      letterSpacing: `${0.2 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h9": {
      fontSize: `${14 / 3.93}vw`,
      lineHeight: `${20 / 3.93}vw`,
      letterSpacing: `${0.35 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".headline-h10": {
      fontSize: `${12 / 3.93}vw`,
      lineHeight: `${16 / 3.93}vw`,
      letterSpacing: `${0.5 / 3.93}vw`,
      fontWeight: "800",
      fontFamily: "obviously-variable",
      fontVariationSettings: '"ital" 0, "wdth" 80, "wght" 800',
    },
    ".body-xl-bold": {
      fontSize: `${20 / 3.93}vw`,
      lineHeight: `${30 / 3.93}vw`,
      letterSpacing: `${0.15 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "bold",
    },
    ".body-xl-medium": {
      fontSize: `${20 / 3.93}vw`,
      lineHeight: `${30 / 3.93}vw`,
      letterSpacing: `${0.2 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "500",
    },
    ".body-xl-regular": {
      fontSize: `${20 / 3.93}vw`,
      lineHeight: `${30 / 3.93}vw`,
      letterSpacing: `${0.25 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "400",
    },
    ".body-l-bold": {
      fontSize: `${16 / 3.93}vw`,
      lineHeight: `${24 / 3.93}vw`,
      letterSpacing: `${0.2 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "bold",
    },
    ".body-l-medium": {
      fontSize: `${16 / 3.93}vw`,
      lineHeight: `${24 / 3.93}vw`,
      letterSpacing: `${0.3 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "500",
    },
    ".body-l-regular": {
      fontSize: `${16 / 3.93}vw`,
      lineHeight: `${24 / 3.93}vw`,
      letterSpacing: `${0.3 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "400",
    },
    ".body-m-bold": {
      fontSize: `${14 / 3.93}vw`,
      lineHeight: `${20 / 3.93}vw`,
      letterSpacing: `${0.15 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "bold",
    },
    ".body-m-medium": {
      fontSize: `${14 / 3.93}vw`,
      lineHeight: `${20 / 3.93}vw`,
      letterSpacing: `${0.25 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "500",
    },
    ".body-m-regular": {
      fontSize: `${14 / 3.93}vw`,
      lineHeight: `${20 / 3.93}vw`,
      letterSpacing: `${0.2 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "400",
    },
    ".body-s-bold": {
      fontSize: `${12 / 3.93}vw`,
      lineHeight: `${16 / 3.93}vw`,
      letterSpacing: `${0.1 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "bold",
    },
    ".body-s-medium": {
      fontSize: `${12 / 3.93}vw`,
      lineHeight: `${16 / 3.93}vw`,
      letterSpacing: `${0.1 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "500",
    },
    ".body-s-regular": {
      fontSize: `${12 / 3.93}vw`,
      lineHeight: `${16 / 3.93}vw`,
      letterSpacing: `${0.1 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "400",
    },
    ".body-xs-bold": {
      fontSize: `${10 / 3.93}vw`,
      lineHeight: `${14 / 3.93}vw`,
      letterSpacing: `${0.5 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "bold",
    },
    ".body-bold": {
      fontSize: `${14 / 3.93}vw`,
      lineHeight: `${20 / 3.93}vw`,
      letterSpacing: `${0.15 / 3.93}vw`,
      fontFamily: "Inter",
      fontWeight: "800",
    },
  };

  // 添加自定义的文字样式类
  addUtilities(newTypographyUtilities);
});
// 导出插件
export { text_typographyPlugin };
